server:
  port: 8010

spring:
  datasource:
    hikari:
      connectionTimeout: 50000
      maximumPoolSize: 2
    ## PostgreSQL
    url: jdbc:postgresql://51.68.44.179:5432/crm
    username: crm_1
    password: BVfBymMVpTVZ
  #drop n create table again, good for testing, comment this in production
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: organization
        ddl-auto: update
    open-in-view: false
